### ISSUE TITLE
夜寝れないのに朝も起きれない。

### ISSUE THREAD

**Issue by yuyahadano** [k1h1github/nagoyaboost2022_dx_handson#15]

**Comment by nakayamashota1215** [comment]
夜走ってみましょう。
アドレナリンが出てすっきりしてその後寝れます

**Comment by keinajk** [comment]
日中に運動してみたらどうでしょうか？

**Comment by yuyahadano** [comment]
@nakayamashota1215 

夜に走ってみるの、良いですね！
最近は読書とゲームで引きこもり気味です泣

**Comment by yuyahadano** [comment]
@keinajk 

ありですね！バレーのサークルに入っているので久しぶりに行こうと思います！！
