### ISSUE TITLE
なかなか痩せない。

### ISSUE THREAD

**Issue by sugi0112** [k1h1github/nagoyaboost2022_dx_handson#16]
どうしても我慢できずにたくさん食べてしまいなかなか痩せることができません。

**Comment by Kosuke-Sh** [comment]
パーソナルトレーニングいいですよ！４か月で-8kgできました！

**Comment by erkwtnb** [comment]
私の周りでは、16時間断食ダイエットが流行っています！

**Comment by sugi0112** [comment]
> パーソナルトレーニングいいですよ！４か月で-8kgできました！

すごい！探してみます！
