### ISSUE TITLE
3歳の娘がアグレッシブ過ぎて，勉強や趣味の時間が夜中 23 時以降しか取れません！

### ISSUE THREAD

**Issue by KazutoMakino** [k1h1github/nagoyaboost2022_dx_handson#21]
掲題の件で，皆さんは，どんなタイミングで趣味や自己研鑽に時間を宛てていますか？

**Comment by emd-masato** [comment]
朝型にシフトしようと思いましたけど、それに合わせて娘も急に早起きになったので深夜に頑張ってます(;'∀')

**Comment by KazutoMakino** [comment]
リアクションありがとうございます．
いつもは，寝かせてから力尽きるまで頑張ってます．
クローズします．

**Comment by kwi0303** [comment]
めっちゃわかります。
自分は妻にお願いして分担しつつ時間確保しています。
