### ISSUE TITLE
コロナ関連の悩み

### ISSUE THREAD

**Issue by itotsubasa1111** [k1h1github/nagoyaboost2022_dx_handson#24]
喉が痛くて咳が出ますが、抗原検査をしたところコロナは陰性でした。
しかしながら不安です。

**Comment by YUKOKAMIYA** [comment]
私も５日間苦しんだ後、PCRで陽性でした。びょういんに行かれることをお勧めしますよ

**Comment by ShinjiKosaka512** [comment]
うちの子は、自前で実施した検査では陰性 → 病院で陽性でした。
ちゃんとしたところで検査してもらうのもいいかもしれません。

**Comment by itotsubasa1111** [comment]
再度病院に行ってみます！
