### ISSUE TITLE
最近寝付きが悪いです。求！安眠方法

### ISSUE THREAD

**Issue by TSUZAKIHIKARI** [k1h1github/nagoyaboost2022_dx_handson#25]
おすすめ安眠方法があれば教えてください。
ヤクルト1000は効いた気がします！

**Comment by electricbaka** [comment]
運動してから寝る

**Comment by erkwtnb** [comment]
Youtubeで528Hz睡眠導入と調べてでてくる動画をBGMにかけておくと寝つきがいいらしいです！

**Comment by mscu1** [comment]
もしNetflix使っていたら、「ヘッドスペースの安らぎガイド」を是非観てみてください！
眠くなる物語とか、入眠しやすい呼吸法とかを教えてくれて聞きながら寝るのお勧めです！

**Comment by SotaJozuka** [comment]
米軍式入眠方法調べてみてください

**Comment by TSUZAKIHIKARI** [comment]
ありがとうございます！
運動した後Youtubeを流しながら米軍式入眠方法で寝ます！

ネトフリ民なのでガイド観てみます！こんなのあるんだすごい！
こちらはじっくりみます！
