### ISSUE TITLE
筋トレ

### ISSUE THREAD

**Issue by inaki-kuma** [k1h1github/nagoyaboost2022_dx_handson#26]
筋トレを続けたいのですが、すぐにあきらめてしまいます。
何か続けられる秘訣を教えてください。

**Comment by Kosuke-Sh** [comment]
別でも書きましたが、パーソナルトレーニングいいですよ！

**Comment by itotsubasa1111** [comment]
毎日お風呂に入る前に全裸で鏡を見るとモチベが上がりますよ笑

**Comment by ykuno26** [comment]
毎日2分だけ……とやると習慣化できます

**Comment by KenshinFutamura** [comment]
周りの人を巻き込んでやると長続きすると思います！
ライバル意識的な

**Comment by SotaJozuka** [comment]
自分の体と対話しましょう

**Comment by cityofnagoya-masaki** [comment]
周りの人に褒めてもらいましょう！

**Comment by inaki-kuma** [comment]
みなさんの意見をまとめて全裸で自分の体と対話し、2分だけやる事にします。
