### ISSUE TITLE
子供が寝付かない

### ISSUE THREAD

**Issue by Dashimaki22** [k1h1github/nagoyaboost2022_dx_handson#29]
### 2歳の寝かしつけ
子供が、眠いのに夜10時まで粘るようになりました。寝かしつけのコツは何か・・・

**Comment by kwi0303** [comment]
お風呂に早めに入れて早く眠たくなるようにするのはどうでしょうか！

**Comment by nakayamashota1215** [comment]
自分はいっそ諦めました・・・
早く寝かせないとと思うほうがある意味ストレスかと思い
とりあえずベッドで横になる→そのうち寝るみたいな感じです

**Comment by Dashimaki22** [comment]
> とりあえずベッドで横になる→そのうち寝るみたいな感じです
本を読む部屋と寝る部屋を分けていますが、夜は寝室で本OKにしてみます。
一旦クローズします。
