### ISSUE TITLE
食べ過ぎてしまう…

### ISSUE THREAD

**Issue by Shinashu** [k1h1github/nagoyaboost2022_dx_handson#30]
最近、ついつい食べ過ぎてしまいます。
どうしたらいいのでしょうか

**Comment by electricbaka** [comment]
食べない
![image](https://user-images.githubusercontent.com/28028427/186411893-97a35973-237f-4765-9720-4015015e5fff.png)

**Comment by sugi0112** [comment]
わかります、、世界がおいしいもので溢れていますよね、、

**Comment by electricbaka** [comment]
@k1h1github アサイン

**Comment by keinajk** [comment]
PFCバランスを意識してみると食べる量が変わると思います
