### ISSUE TITLE
社会人2年目になっても朝型人間になれません

### ISSUE THREAD

**Issue by mscu1** [k1h1github/nagoyaboost2022_dx_handson#32]
学生時代ずっと夜型人間だったせいか、未だに毎朝死に物狂いで自分をたたき起こしています。
本当は6時半に起きたいけど、頑張って7時半起きの毎日です。

**Comment by electricbaka** [comment]
朝日を浴びる

**Comment by Kosuke-Sh** [comment]
歳を重ねれば自然と朝方になります。。。。

**Comment by sibucho86** [comment]
朝起きた際に布団の中で全力でモゾモゾすると
強制的に血流を促進できるので、すっきり目が覚めるらしいですよ。

**Comment by ykuno26** [comment]
夜早く寝ましょう

**Comment by ryukitokai** [comment]
朝の楽しみをもてばいいのではないでしょうか！
(ex)コーヒーやスムージーなどの趣味を持つ

**Comment by NnnhH** [comment]
寝る前にリポビタンDを飲むといいらしいです

**Comment by mscu1** [comment]
> 朝日を浴びる

コメントありがとうございます！
カーテン開けっ放しで朝日入れるようにはしてるのですが、爆睡過ぎるのか届いてないみたいです。。

**Comment by mscu1** [comment]
> 歳を重ねれば自然と朝方になります。。。。

時間の経過とともに、でしょうか…

**Comment by mscu1** [comment]
> 朝起きた際に布団の中で全力でモゾモゾすると 強制的に血流を促進できるので、すっきり目が覚めるらしいですよ。

血流の促進！試したことが無かったので、早速明日試してみます！
