### ISSUE TITLE
理不尽な上司とのうまい付き合い方

### ISSUE THREAD

**Issue by erkwtnb** [k1h1github/nagoyaboost2022_dx_handson#38]
納得いかない！ような説教をされたら、みなさんはどうやって気持ちを晴らしていますか？

**Comment by ykuno26** [comment]
その人の幸せを祈ると怒りが消えていきます。むかつくけど。

**Comment by nakayamashota1215** [comment]
運動でストレス解消はどうでしょう？？
自分も走りながらバカヤローと叫んだりしてます

**Comment by KenshinFutamura** [comment]
とにかく寝て忘れます。嫌というほど寝てイライラを忘れます。

**Comment by ShinjiKosaka512** [comment]
昔はよく、通勤のクルマの中で叫んでました。

**Comment by NnnhH** [comment]
イライラしたエネルギーでジョギングを始めたことがあります。
続きませんでしたが。。。

**Comment by erkwtnb** [comment]
ありがとうございました！！
