### ISSUE TITLE
最近毎日中途覚醒する

### ISSUE THREAD

**Issue by ykuno26** [k1h1github/nagoyaboost2022_dx_handson#9]
毎日中途覚醒して毎日寝不足です。困った困った

**Comment by cityofnagoya-masaki** [comment]
クーラー入れて、めぐりズムのアイマスクつけて寝るのがおすすめです！

**Comment by ykuno26** [comment]
クーラーいれてめぐりずむのアイマスクつけてます！アイマスク高いので毎日つけられないのが問題なので稼ぎますかね……
